from enum import Enum
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field


class SignalType(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    WATCH = "WATCH"


def calculate_risk_reward_ratio(
    entry_price: Optional[float],
    stop_loss: Optional[float],
    target_price: Optional[float],
    signal: SignalType = SignalType.BUY,
) -> Optional[float]:
    """
    Helper function to calculate Risk-to-Reward ratio.
    For BUY: (target_price - entry_price) / (entry_price - stop_loss)
    For SELL: (entry_price - target_price) / (stop_loss - entry_price)
    """
    if entry_price is None or stop_loss is None or target_price is None:
        return None

    if signal == SignalType.BUY:
        risk = entry_price - stop_loss
        reward = target_price - entry_price
    elif signal == SignalType.SELL:
        risk = stop_loss - entry_price
        reward = entry_price - target_price
    else:
        return None

    if risk <= 0 or reward < 0:
        return None

    return round(reward / risk, 2)


class StrategySignal(BaseModel):
    """
    Structured data model representing a signal generated by a trading strategy.
    """
    symbol: str
    strategy_name: str
    strategy_version: str
    signal: SignalType
    signal_date: str  # YYYY-MM-DD
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    target_price: Optional[float] = None
    risk_reward: Optional[float] = None
    score: Optional[float] = Field(default=None, description="Confidence score (0.0 to 1.0 or 0 to 100)")
    reason: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)

    def model_post_init(self, __context: Any) -> None:
        """Auto-computes risk_reward if entry, stop_loss, and target_price are provided."""
        if self.risk_reward is None and self.entry_price and self.stop_loss and self.target_price:
            self.risk_reward = calculate_risk_reward_ratio(
                self.entry_price, self.stop_loss, self.target_price, self.signal
            )
